export const EnglishBoneName = [
  "every parent",
  "center",
  "groove",
  "lower body",
  "left foot",
  "left knee",
  "left ankle",
  "left toe",
  "right foot",
  "right knee",
  "right ankle",
  "right toe",
  "lower part of the body",
  "Skirt_0_0",
  "Skirt_1_0",
  "skirt_2_0",
  "Skirt_0_1",
  "skirt_1_1",
  "Skirt_2_1",
  "Skirt_0_2",
  "skirt_1_2",
  "skirt_2_2",
  "Skirt_0_3",
  "skirt_1_3",
  "skirt_2_3",
  "Skirt_0_4",
  "skirt_1_4",
  "skirt_2_4",
  "Skirt_0_5",
  "skirt_1_5",
  "skirt_2_5",
  "Skirt_0_6",
  "Skirt_1_6",
  "skirt_2_6",
  "Skirt_0_7",
  "Skirt_1_7",
  "skirt_2_7",
  "Skirt_0_8",
  "Skirt_1_8",
  "skirt_2_8",
  "Skirt_0_9",
  "skirt_1_9",
  "skirt_2_9",
  "upper body",
  "Upper body 2",
  "neck",
  "head",
  "both eyes",
  "both ends",
  "right eye",
  "right-hand corner",
  "left eye",
  "left-hand corner",
  "head",
  "forelock",
  "stupid hair A",
  "furry hair B",
  "Left Side Hair 1",
  "Left Side Hair 2",
  "Left Side Hair 3",
  "Left Side Hair 4",
  "Left Side Hair 5",
  "Right side hair 1",
  "Right side hair 2",
  "Right side hair 3",
  "Right side hair 4",
  "Right side hair 5",
  "Back hair 1",
  "Back hair 2",
  "Back hair 3",
  "Back hair 4",
  "Left shoulder P",
  "left shoulder",
  "Left shoulder C",
  "left arm",
  "left arm screw",
  "left elbow",
  "left hand screw",
  "left wrist",
  "Left thumb 0",
  "Left thumb 1",
  "Left thumb 2",
  "left parent fingertip",
  "Left Finger 1",
  "Left Finger 2",
  "Left Finger 3",
  "left-handed fingertip",
  "Left middle finger 1",
  "Left middle finger 2",
  "Left middle finger 3",
  "left middle fingertip",
  "Left ring finger 1",
  "Left ring finger 2",
  "Left ring finger 3",
  "left tip of the drug",
  "Left little finger 1",
  "Left little finger 2",
  "Left little finger 3",
  "left small fingertip",
  "left-hand tip",
  "Left hand screw 1",
  "Left hand screw 2",
  "Left hand screw 3",
  "Left arm screw 1",
  "Left arm screw 2",
  "Left arm screw 3",
  "Right shoulder P",
  "right shoulder",
  "Right shoulder C",
  "right arm",
  "right arm screw",
  "right elbow",
  "right hand screw",
  "right wrist",
  "Right thumb 0",
  "Right thumb 1",
  "Right thumb 2",
  "right parent fingertip",
  "Right Finger 1",
  "Right Finger 2",
  "Right Finger 3",
  "right index fingertip",
  "Right middle finger 1",
  "Right middle finger 2",
  "Right middle finger 3",
  "right middle fingertip",
  "Right ring finger 1",
  "Right ring finger 2",
  "Right ring finger 3",
  "right tip of the drug",
  "Right little finger 1",
  "Right little finger 2",
  "Right little finger 3",
  "right small fingertip",
  "right hand tip",
  "Right hand screw 1",
  "Right hand screw 2",
  "Right hand screw 3",
  "Right arm screw 1",
  "Right arm screw 2",
  "Right arm screw 3",
  "two points of the upper body",
  "center destination",
  "Left foot IK",
  "Left toe IK",
  "Left toe IK tip",
  "Left foot IK tip",
  "Right foot IK",
  "Right toe IK",
  "Right toe IK tip",
  "Right foot IK tip",
];
